### ISSUE TITLE
v3.4.7 missing from NPM

### ISSUE THREAD

**Issue by vinnymac** [ReactTraining/react-stdio#18]
### Summary
It appears the [latest version](https://github.com/ReactTraining/react-stdio/releases/tag/v3.4.7) published under releases at the time of writing is not currently on npm.

When I run `npm show react-stdio` or `yarn info react-stdio` I do not see any `3.4.7` version, and the latest says `3.4.6`. If you could update the registry to include the latest release that would be very helpful.

I was hoping to upgrade to easily escape the `event-stream` vulnerable dependency that was included here. Let me know if I am missing something, thank you.

**Comment by mjackson** [comment]
Thanks for bringing this to my attention, @vinnymac. The 3.4.7 release failed because of a bad npm auth token. [I just released 3.4.8](https://travis-ci.org/ReactTraining/react-stdio/builds/467156204), which was successfully published to npm.
